name: Profile Analytics Dashboard

on:
  schedule:
    - cron: "0 0 * * *" # Daily at midnight
  workflow_dispatch:

jobs:
  generate-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate GitHub Stats
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROJECTS: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_TIMEZONE: "True"
          SHOW_EDITORS: "True"
          SHOW_LANGUAGE_PER_REPO: "True"
          SHOW_LOC_CHART: "False"

      - name: Update Profile Views
        run: |
          # Create a simple view counter
          COUNT_FILE="profile_views.txt"
          if [ -f "$COUNT_FILE" ]; then
            CURRENT_COUNT=$(cat $COUNT_FILE)
          else
            CURRENT_COUNT=0
          fi
          NEW_COUNT=$((CURRENT_COUNT + 1))
          echo $NEW_COUNT > $COUNT_FILE

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "📊 Update profile analytics"
          git push
