name: Update README with Dynamic Content

on:
  schedule:
    # Runs every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update README with latest blog posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "BLOG"
          feed_list: "https://dev.to/feed/crayfish0"

      - name: Update README with quotes
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "QUOTE"
          feed_list: "https://quotes.rest/qod"

      - name: Update weather
        run: |
          WEATHER=$(curl -s "https://wttr.in/YourCity?format=3")
          echo "Current weather: $WEATHER" >> temp_weather.txt

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "🤖 Auto-update README with latest content"
          git push
